version: "3.7"

volumes:
  python-venv:

services:
  python:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APP_USER: ${USER?USER}
        APP_USER_ID: ${USER_ID?USER_ID}
        APP_USER_HOME: ${HOME?HOME}
        APP_GROUP: ${GROUP?GROUP}
        APP_GROUP_ID: ${GROUP_ID?GROUP_ID}
    volumes:
      - python-venv:/venv
      - /var/run/docker.sock:/var/run/docker.sock
      - $HOME/.ssh:$HOME/.ssh
      - $PWD:$PWD
    working_dir: $PWD
    network_mode: host
